# Generated by Django 3.0.7 on 2022-06-26 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0011_studentgroup_student_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='student_list',
            field=models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator('(([A-Z]{1,2}\\d{6})+)(,\\s*([A-Z]{1,2}\\d{6})+)*')]),
        ),
    ]
