# Generated by Django 3.0.7 on 2022-06-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0012_auto_20220626_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='department',
            field=models.CharField(choices=[('KIF', 'Kif'), ('DIF', 'Dif'), ('AX', 'Ax'), ('TELEKOM', 'Telekom')], max_length=10),
        ),
    ]
