# Generated by Django 3.0.7 on 2022-06-26 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0014_document_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='user',
            new_name='author',
        ),
    ]
