# Generated by Django 3.0.7 on 2022-06-26 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thesis', '0015_auto_20220626_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
