# Generated by Django 3.0.7 on 2022-06-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_auto_20200908_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('KIF', 'Kif'), ('DIF', 'Dif'), ('AX', 'Ax'), ('TELEKOM', 'Telekom')], default='KIF', max_length=10),
        ),
    ]
